CandyMaker/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'CandyMaker'
urlpatterns = [
    path('startmaker/<str:param>/', views.startmaker, name='startmaker'),
]

EyeCandy_Web/urls.py
from django.contrib import admin
from django.urls import path
from. import views

app_name = 'EyeCandy_Web'
urlpatterns = [
    path('', views.index, name='index'),
    path('analyse/', views.analyse, name='analyse'),
    path('gallery/', views.gallery, name='gallery'),
    path('result/<int:image_pk>/', views.result, name='result'),
    path('savetogallery/<int:image_pk>', views.savetogallery, name='savetogallery'),

]

FlashWoman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('CandyMaker/', include('CandyMaker.urls')),
    path('EyeCandy_Web/', include('EyeCandy_Web.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CandyMaker/models.py
from django.db import models

# Create your models here.

EyeCandy_Web/models.py
from django.db import models
import os
from django.conf import settings
from imagekit.models import ProcessedImageField, ProcessedImageField
from imagekit.processors import Thumbnail

class Image(models.Model):
    name = models.CharField(max_length=200)
    origin = models.ImageField('Input', upload_to='origin')
    result = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    to_gallery = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.id}, {self.origin}'

CandyMaker/views.py
import os
import cv2 as cv
from django.shortcuts import render,redirect
from django.conf import settings
from CandyMaker.bookshelf.function.contours import contours
from CandyMaker.bookshelf.function.preprocessing import preprocessing

# from django.conf import settings

def startmaker(request, param):
    # 0. get params : 2+ 이미지 full 주소 + pk
    #row = int(param.split('+')[0])
    row = 4
    img_url = param.split('+')[1]
    pk = int(param.split('+')[2])

    print(row, img_url, pk )

    ############################## 시연을 위한 로직 : mask를 찾기 위함 (html에 opencv window 출력 불가)
    filename= img_url.split('.')[0] #imagename_dslkfjlaew.jpg -> imagename
    mask_path = os.path.join(settings.BASE_DIR, 'CandyMaker', 'img', 'masks', f'{filename}_mask.jpg')
    ###################################################################################################
    print(filename, mask_path)

    # 1. load image
    img = cv.imread(mask_path)
    img_org = cv.imread(img_url)
    print('1')

    # 2. preprocess img
    # img = preprocessing(img)
    print('2')


    print('gi')
    return redirect('EyeCandy_Web:result', pk)

EyeCandy_Web/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Image
from django.conf import settings
import os
import io

def index(request):
    return render(request, 'EyeCandy_Web/index.html')

def analyse(request):
    rows = request.POST.get('how-many') # 책장 row 수
    origin = request.FILES.get('file')
    name = origin.name
    # print(origin.name)

    # 1.input 이미지 저장
    image = Image(name=name, origin=origin)
    image.save() #print(image.origin.name)

    # openCV
    param = f'{rows}+{name}+{image.pk}'  # 4 + test1.jpg + 5
    return redirect('CandyMaker:startmaker', param)


def result(request, image_pk):
    from .models import Image
    # 저장된 결과 이미지 가져오기
    image = Image.objects.get(pk=image_pk)

    output_path =f'/media/output/output_{image.name}'
    print(output_path)
    # 저장된 결과 이미지 result 컬럼에 저장
    image.result = output_path
    image.save()
    from .models import Image
    # 재확인 후 context 저장
    image = get_object_or_404(Image, pk=image_pk)
    context = {'image': image}
    return render(request, 'EyeCandy_Web/result.html', context)

def savetogallery(request, image_pk):
    image = Image.objects.get(pk=image_pk)
    image.to_gallery = True
    image.save()
    return redirect('EyeCandy_Web:gallery')

def gallery(request):
    # 갤러리로 보여줄 것들만 가져온다.
    images = Image.objects.filter(to_gallery = True)
    print('here: ', images)
    last = Image.objects.last()

    context= {'images':images, 'last':last }
    return render(request, 'EyeCandy_Web/gallery.html', context)

EyeCandy_Web/templates/EyeCandy_Web/Board.html
{% extends 'base.html'%}
{% load static %}
{% block body %}
<h1>This is Gallery!</h1>
{% endblock %}

EyeCandy_Web/templates/EyeCandy_Web/People.html
{% extends 'base.html'%}
{% load static %}
{% block body %}
<h1>This is Gallery!</h1>
{% endblock %}

EyeCandy_Web/templates/EyeCandy_Web/Support.html
{% extends 'base.html'%}
{% load static %}
{% block body %}
<h1>This is Gallery!</h1>
{% endblock %}

EyeCandy_Web/templates/EyeCandy_Web/gallery.html
{% extends 'base.html'%}
{% load static %}
{% block body %}

<body>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{% static '/js/gallery.js' %}"    ></script>
    <div id="container" >
        <main>
            <div id="gallery">
                <div id="gallery-container">
                    <div id="gallery-prev-button">
                        <i class="material-icons" >
                            <
                        </i>
                    </div>
                    <div id="gallery-main-picture" style="background-image:url('{{last.result}}');">

                    </div>
                    <div id="gallery-next-button">
                        <i class="material-icons">
                            >
                        </i>
                    </div>
                </div>
                <div id="gallery-other-item-container">
                    <input type="hidden" id="page" value="1" />
                    {% for img in images %}
                        <div class='gallery-other-item active' style="background-image:url('{{ img.result }}')" data-page="{{ forloop.counter }}" data-src='{{img.result}}'></div>
                    {% endfor %}
                </div>
            </div>

        </main>
    </div>
</body>


{% endblock %}

EyeCandy_Web/templates/EyeCandy_Web/index.html
{% extends 'base.html'%}
{% load static %}
{% block body %}
                <div id="page-1" class="page active">
                    <div id="eye-candy-pic">
                        <img src= "{% static '/images/books.png' %}" >
                    </div>
                    <div id='eye-candy-content'>
                        <h2>Beautify Your Book shelf</h2>

                        <div>
                            <button id="main-button" onclick="toPage(2)">Start</button>
                        </div>
                    </div>
                </div>

                <div id="page-2"  class="page">
                    <div id="picture-container">
                        <div class='image-viewer' style="border:1px solid #eee;">
                            <div id="image-viewer-text">Upload your Image file</div>
                            <img id="image" style="width:auto;height:100%;">
                        </div>
                    </div>

                    <form action="/EyeCandy_Web/analyse/" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" id="file" name = "file" accept="image/*" style="display:none;">
                        <div id="page-2-button-container">
                            <div>
                                <div id="upload-button" onclick="openFile()">Upload</div>
                            </div>
<!--                            <div id="select-container">-->
<!--                                <label for="how-many">How many rows? </label>-->
<!--                                <select id='how-many' name = 'how-many'>-->
<!--                                    <option value="1">1</option>-->
<!--                                    <option value="2">2</option>-->
<!--                                    <option value="3">3</option>-->
<!--                                    <option value="4">4</option>-->
<!--                                    <option value="5">5</option>-->
<!--                                    <option value="6">6</option>-->
<!--                                </select>-->
<!--                            </div>-->

                            <div  >
                                <input type="submit" id="figure-button"  style="margin-top:5px;" , value="GO!"></input>
                            </div>


                        </div>
                    </form>
                </div>


{% endblock %}

EyeCandy_Web/templates/EyeCandy_Web/result.html
{% extends 'base.html'%}
{% load static %}
{% block body %}
                <div id="page">
                        <div id="picture-container">
                            <div class='result-image-viewer'>
<!--                                <img src = "{{ image.origin.url }}" id="image-before" >-->
<!--                                <img src = "{% static '/images/icons-arrow1.png' %}" id="result-arrow">-->
                                <img src = "{{ image.result }}" id="image-after" name="image"  >
                            </div>
                        </div>

                        <div id='result-content'>
                                <div>
                                    <a href="{% url 'EyeCandy_Web:savetogallery' image.pk %}"> <button type="submit" id="main-button">Save to Gallery</button></a>
                                </div>
                        </div>
                </div>

{% endblock %}

FlashWoman/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href= "{% static '/css/index.css' %}" >
    <title>Eye Candy</title>
    <script
  src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
    <script src="{% static '/js/index.js' %}"></script>
</head>
<body>
    <div id="container" >
        <header>
            <ul id="menu-container">
                <li class="menu logo"> <a href="{% url 'EyeCandy_Web:index' %}"> <span style="color:rgb(217,44,71)">EYE</span>CANDY </a></li>
<!--                <li class="menu">People</li>-->
                <li class="menu"><a href="{% url 'EyeCandy_Web:gallery' %}">Gallery</a></li>
<!--                <li class="menu">Board</li>-->
<!--                <li class="menu">Support</li>-->
            </ul>
        </header>
        <main>
            <div id="eye-candy">
                {% block body %}

                {% endblock %}
            </div>
        </main>
    </div>
</body>
</html>